#ifndef ROCK_FUNCTIONS_GUARD
#define ROCK_FUNCTIONS_GUARD

void CharacterSelection();
void CharacterColorSelection();
void Reset();
void ChangeColor();
void MissileMovement();
void MissileForm();
void MissileCollision();
void UpdateDwarf();
void Credits();
void InstructionsOne();
void InstructionsTwo();
void Instructions();
void KeyToChooseModel();
void KeyToChooseColor();
void PicksDwarfProperties();
void ReturnToMenu();
void LoadGame();
void PrintOptionsMenu();
void OptionsMenuKey();
void Options();
void MainMenuKey();
void PrintMainMenu();
void MainMenu();
void AdjustDifficulty();
void SetDifficulty();
void OutputOfAndromedaSkill();
void OutputOfFireSkill();
void OutputOfChangeLevel();
void ChangeLevel();
void CreatingPowups();
void CreatingRocks();
void InGameMenu();
void AndromedaSkill();
void OnFireClick();
void UpdateDwarfCoordinates();
void CheckForRockAndPowupIntersection(int&);
void AddingPowupWithDifShapes();
void RocksShapeAndColor();
void FireDuration();
void Update();
void Draw();
void AfterCollision();
void Collision();
void DwarfPrevStatus();
void OutputOfFasterBonus();
void OutputOfShrinkBonus();
void OnPowupsCollision();
void PowupCollsion();
void InGameMenuKey();
void PrintInGameMenu();
void ReturnToInGameMenu();
void SaveGame();
void SkillDuration();
int main();

#endif